import React, { useState } from "react";
import { 
  FileCheck2, 
  Download, 
  Printer, 
  Copy, 
  Check, 
  Layers, 
  Sparkles, 
  AlertCircle,
  FolderOpen
} from "lucide-react";
import jsPDF from "jspdf";

export default function DocumentChecklist({ consolidatedDocs, directMatches, nearMissMatches }) {
  const [checkedDocs, setCheckedDocs] = useState({});
  const [copied, setCopied] = useState(false);

  if (!consolidatedDocs || consolidatedDocs.total_unique_documents === 0) {
    return (
      <div className="bg-white rounded-2xl border border-slate-200 p-8 text-center">
        <FolderOpen className="w-10 h-10 text-slate-400 mx-auto mb-3 opacity-60" />
        <h3 className="font-bold text-slate-800 text-sm">No Document Checklist Available</h3>
        <p className="text-xs text-slate-500 mt-1">
          Complete the eligibility evaluation to generate your consolidated document checklist.
        </p>
      </div>
    );
  }

  const { universal_documents, scheme_specific_documents, total_unique_documents } = consolidatedDocs;

  const toggleCheck = (docName) => {
    setCheckedDocs((prev) => ({
      ...prev,
      [docName]: !prev[docName],
    }));
  };

  const completedCount = Object.values(checkedDocs).filter(Boolean).length;
  const progressPercent = Math.min(
    100,
    Math.round((completedCount / Math.max(1, total_unique_documents)) * 100)
  );

  const handleCopyMarkdown = () => {
    let md = `# 📋 Government Scheme Application Document Checklist\n\n`;
    md += `**Readiness Progress:** ${completedCount} / ${total_unique_documents} documents prepared (${progressPercent}%)\n\n`;
    
    md += `## 🌟 Universal Documents (Shared Across All Schemes)\n`;
    universal_documents.forEach((doc) => {
      const isChecked = checkedDocs[doc] ? "[x]" : "[ ]";
      md += `- ${isChecked} ${doc}\n`;
    });

    md += `\n## 📁 Scheme-Specific Mandatory Documents\n`;
    Object.entries(scheme_specific_documents).forEach(([schemeName, docs]) => {
      md += `\n### ${schemeName}\n`;
      docs.forEach((doc) => {
        const isChecked = checkedDocs[doc] ? "[x]" : "[ ]";
        md += `- ${isChecked} ${doc}\n`;
      });
    });

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleExportPDF = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42); // slate-900
    doc.text("Government Scheme Application Document Checklist", 14, 20);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(`Generated by GovScheme.AI - Total Unique Documents: ${total_unique_documents}`, 14, 27);
    doc.text(`Prepared: ${completedCount} of ${total_unique_documents} (${progressPercent}% ready)`, 14, 33);

    let y = 43;

    // Universal Docs
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59);
    doc.text("1. Universal Documents (Required for Most Applications)", 14, y);
    y += 7;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    universal_documents.forEach((item) => {
      if (y > 275) {
        doc.addPage();
        y = 20;
      }
      const checkMark = checkedDocs[item] ? "[READY]" : "[PENDING]";
      doc.setTextColor(checkedDocs[item] ? 16 : 71, checkedDocs[item] ? 185 : 85, checkedDocs[item] ? 129 : 105);
      doc.text(`${checkMark}`, 16, y);
      doc.setTextColor(51, 65, 85);
      doc.text(`  ${item}`, 35, y);
      y += 6;
    });

    y += 5;

    // Scheme Specific Docs
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59);
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    doc.text("2. Scheme-Specific Documents", 14, y);
    y += 7;

    Object.entries(scheme_specific_documents).forEach(([schemeName, docs]) => {
      if (y > 265) {
        doc.addPage();
        y = 20;
      }
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(3, 105, 161);
      doc.text(`• ${schemeName}:`, 16, y);
      y += 5;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      docs.forEach((item) => {
        if (y > 275) {
          doc.addPage();
          y = 20;
        }
        const checkMark = checkedDocs[item] ? "[READY]" : "[PENDING]";
        doc.setTextColor(checkedDocs[item] ? 16 : 71, checkedDocs[item] ? 185 : 85, checkedDocs[item] ? 129 : 105);
        doc.text(`${checkMark}`, 20, y);
        doc.setTextColor(71, 85, 105);
        doc.text(`  ${item}`, 40, y);
        y += 5.5;
      });
      y += 3;
    });

    doc.save("GovScheme_Required_Documents_Checklist.pdf");
  };

  return (
    <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-5 sm:p-6">
      
      {/* Header & Controls */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-slate-100 pb-5 mb-5">
        <div>
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-emerald-100 text-emerald-800 flex items-center justify-center font-bold">
              <FileCheck2 className="w-5 h-5 text-emerald-700" />
            </div>
            <h3 className="font-extrabold text-base sm:text-lg text-slate-900">
              Required Documents Checklist
            </h3>
          </div>
          <p className="text-xs text-slate-500 mt-1">
            Deduplicated & consolidated across all {directMatches?.length || 0} eligible schemes
          </p>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-2">
          <button
            onClick={handleCopyMarkdown}
            className="flex items-center gap-1.5 text-xs font-semibold text-slate-700 hover:text-slate-900 bg-slate-100 hover:bg-slate-200 px-3 py-2 rounded-lg transition-colors"
            title="Copy checklist in markdown format"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? "Copied!" : "Copy MD"}</span>
          </button>

          <button
            onClick={handleExportPDF}
            className="flex items-center gap-1.5 text-xs font-bold text-white bg-blue-600 hover:bg-blue-700 px-3.5 py-2 rounded-lg shadow-sm shadow-blue-500/20 transition-all hover:translate-y-[-1px]"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download PDF</span>
          </button>

          <button
            onClick={() => window.print()}
            className="flex items-center gap-1.5 text-xs font-semibold text-slate-700 hover:text-slate-900 bg-slate-100 hover:bg-slate-200 px-3 py-2 rounded-lg transition-colors"
          >
            <Printer className="w-3.5 h-3.5" />
            <span className="hidden sm:inline">Print</span>
          </button>
        </div>
      </div>

      {/* Progress Bar */}
      <div className="bg-slate-50 rounded-xl p-4 mb-6 border border-slate-200/80">
        <div className="flex items-center justify-between text-xs font-bold text-slate-700 mb-2">
          <span>Application Readiness Progress:</span>
          <span className="text-emerald-700">
            {completedCount} of {total_unique_documents} documents ready ({progressPercent}%)
          </span>
        </div>
        <div className="w-full h-3 bg-slate-200 rounded-full overflow-hidden">
          <div
            className="h-full bg-gradient-to-r from-blue-600 to-emerald-500 transition-all duration-300 rounded-full"
            style={{ width: `${progressPercent}%` }}
          />
        </div>
      </div>

      {/* Group 1: Universal Documents */}
      <div className="mb-6">
        <div className="flex items-center gap-2 mb-3">
          <span className="text-xs font-extrabold uppercase tracking-wider text-slate-800 bg-blue-50 text-blue-800 border border-blue-200 px-2.5 py-0.5 rounded-md">
            🌟 Universal Documents (Required across most schemes)
          </span>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5">
          {universal_documents.map((doc, idx) => {
            const isChecked = Boolean(checkedDocs[doc]);
            return (
              <label
                key={idx}
                className={`flex items-start gap-3 p-3 rounded-xl border transition-all cursor-pointer select-none ${
                  isChecked
                    ? "bg-emerald-50/70 border-emerald-300 text-emerald-950 font-medium shadow-xs"
                    : "bg-white hover:bg-slate-50 border-slate-200 text-slate-700"
                }`}
              >
                <input
                  type="checkbox"
                  checked={isChecked}
                  onChange={() => toggleCheck(doc)}
                  className="mt-0.5 w-4 h-4 text-emerald-600 rounded border-slate-300 focus:ring-emerald-500 cursor-pointer"
                />
                <span className="text-xs leading-relaxed font-semibold">{doc}</span>
              </label>
            );
          })}
        </div>
      </div>

      {/* Group 2: Scheme Specific Documents */}
      {Object.keys(scheme_specific_documents).length > 0 && (
        <div>
          <div className="flex items-center gap-2 mb-3">
            <span className="text-xs font-extrabold uppercase tracking-wider text-slate-800 bg-amber-50 text-amber-900 border border-amber-200 px-2.5 py-0.5 rounded-md">
              📁 Scheme-Specific Mandatory Proofs
            </span>
          </div>
          
          <div className="space-y-4">
            {Object.entries(scheme_specific_documents).map(([schemeName, docs], idx) => (
              <div key={idx} className="border border-slate-200/80 rounded-xl p-4 bg-slate-50/50">
                <h4 className="text-xs font-bold text-slate-800 mb-2.5 flex items-center gap-1.5">
                  <span className="w-2 h-2 rounded-full bg-blue-600" />
                  {schemeName}
                </h4>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                  {docs.map((doc, dIdx) => {
                    const isChecked = Boolean(checkedDocs[doc]);
                    return (
                      <label
                        key={dIdx}
                        className={`flex items-start gap-3 p-2.5 rounded-lg border transition-all cursor-pointer select-none ${
                          isChecked
                            ? "bg-emerald-50/80 border-emerald-300 text-emerald-950 font-medium"
                            : "bg-white hover:bg-slate-50 border-slate-200 text-slate-700"
                        }`}
                      >
                        <input
                          type="checkbox"
                          checked={isChecked}
                          onChange={() => toggleCheck(doc)}
                          className="mt-0.5 w-4 h-4 text-emerald-600 rounded border-slate-300 focus:ring-emerald-500 cursor-pointer"
                        />
                        <span className="text-xs leading-relaxed">{doc}</span>
                      </label>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

    </div>
  );
}
